---
title: "Elementos intermedios de programación en R"
author: "Irvin Rojas"
date: "6 de febrero de 2021"
header-includes:
  - \usepackage{tikz}
  - \usetikzlibrary{shapes, shadows,arrows}
output:
  xaringan::moon_reader:
    css: [default, "libs/cide_titulo_largo.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
        scroll: false
---

class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")
library(tidyverse)
library(magick)
library(reticulate)
xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

.title[
# Sesión 7. Elementos intermedios de programación en R
]

.subtitle[
## Estadística y Econometría en R
]

.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

---
# Agenda

En esta sesión pondremos en práctica lo que hemos aprendido hasta ahora

Usaremos datos para construir variables

Generaremos gráficas más complicadas que las de la clase anterior

---

# Ejercicio 1

1. Parta de la base *mundata.csv*

1. Construya un objeto llamado *sundata* que agregue las características a nivel SUN

1. Descarte la SUN "Colima-Villa de Álvarez" (cause problemas al graficar porque tiene largos periodos sin fallecimientos, afortunadamente)

1. Añada una variable llamada *top.size* que identifique a las 50 ciudades más grandes de México de acuerdo a su población, sin incluir a la ciudad de 

---

# Ejercicio 2

1. Use la base *cases.sintomas.csv*. Esta base contiene los casos diarios confirmados de covid-19 por inicio de síntomas en cada municipio de México. Es un panel de datos porque cada municipio tiene datos diarios de 2020 y 2021

1. Reemplace los casos NA por ceros

1. Agregue el número de casos a nivel SUN

1. Genere una variable *cases.acc* que cuente los datos acumulados hasta el día $t$. Es decir, la suma de casos acumulados hasta ayer, más los de hoy

1. Genere una variable  *cases.growth* que indique la tasa de crecimiento de casos de un día al otro

1. Use la base *mundata* con *top.size* del Ejercicio 1 para quedarse solo con las 50 SUN más grandes de México

1. Instale y llame el paquete *lubridate* para poner en formato de fecha la variable **date**


---

# Ejercicio 3

1. La curva epidémica es una gráfica que muestra el número de casos diarios confirmados

1. Con el data.frame cases.sintomas, construya la curva epidémica del Valle de México

1. Utilice las siguientes funciones para dar formato a su gráfico

- geom_smooth
- xlab
- ylab
- scale_x_date
- labs
- theme


---

# Ejercicio 4

1. Haga ahora el gráfico de la curva epidémica para cada una de las 50 ciudades más grandes usando facetas


---

# Ejercicio 5

1. Repita el gráfico del Ejercicio 4 ahora para la tasa de crecimiento de los casos (**cases.growth**)

1. Repita el gráfico del Ejercicio 4 ahora para la tasa de crecimiento de los fallecimientos (**deaths.growth**)



---

# Próxima clase

Haremos una revisión de la teoría asintótica sobre la que recaen los resultados más importantes de econometría

---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**